<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Meziantou.Analyzer" Version="2.0.188" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="9.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="NuGet.Protocol" Version="6.13.2" />
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.6.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageVersion Include="Pkg1" Version="1.0.1" />
    <PackageVersion Include="Roslynator.Core" Version="4.13.1" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.7.0.110445" />
  </ItemGroup>
</Project>