<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
    <PackageVersion Include="Azure.Identity" Version="1.13.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Duende.AccessTokenManagement" Version="3.2.0" />
    <PackageVersion Include="HtmlAgilityPack" Version="1.11.74" />
    <PackageVersion Include="IdentityModel" Version="7.0.0" />
    <PackageVersion Include="MailKit" Version="4.10.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Graph" Version="5.71.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.6.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Serilog.Enrichers.Demystifier" Version="1.0.3" />
    <PackageVersion Include="Serilog.Sinks.ApplicationInsights" Version="4.0.0" />
    <PackageVersion Include="SmtpServer" Version="10.0.1" />
  </ItemGroup>
</Project>